export const FETCH_TODO = "FETCH_TODO";
export const ADD_TODO = "ADD_TODO";
export const CLEAR_COMPLETED_TODO = "CLEAR_COMPLETED_TODO";
export const ADD_AS_A_COMPLETE_TODO = "ADD_AS_A_COMPLETE_TODO";
export const EDIT_TODO = "EDIT_TODO";
export const DELETE_TODO = "DELETE_TODO";